#ifndef _DEFINE
#define _DEFINE

// General
#define LENGTH 80

// informacion del super administrador
#define SUPER_ADMIN_USUARIO "c"
#define SUPER_ADMIN_PASSWORD "med"
#define SUPER_ADMIN_ACCESO 1

// teclas
#define ENTER 13
#define BACKSPACE 8
#define ARRIBA 80
#define ABAJO 72

// MENUS
#define MENU_PRINCIPAL "MENU_PRINCIPAL"
#define MENU_PERFIL_ADMIN "MENU_PERFIL_ADMIN"
#define MENU_PERFIL "MENU_PERFIL"
#define MENU_ACTUALIZAR_USER "MENU_ACTUALIZAR_USER"
#define MENU_ACTUALIZAR_PELICULA "MENU_ACTUALIZAR_PELICULA"

// registros
#define REGISTRO_USUARIO "REGISTRO_USUARIO"
#define REGISTRO_PELICULA "REGISTRO_PELICULA"

// ARCHIVOS
#define ARCHIVO_USUARIOS "Usuarios"
#define ARCHIVO_PELICULAS "Pelicula"
#define ARCHIVO_SALAS "Salas"
#define ARCHIVO_REPORTES "Reportes"
#define ARCHIVO_TEMP "Tmp"

#endif // _DEFINE